"""Regenerate PROBLEMS.md from the YAML frontmatter in every problems/*/question.md.

Run from repo root:
    python3 scripts/build_index.py            # rewrite PROBLEMS.md
    python3 scripts/build_index.py --check    # exit 1 if PROBLEMS.md is stale

Frontmatter contract (each problems/NNN-slug/question.md must start with):

    ---
    id: 1
    title: Design a URL Shortener
    category: Basics
    topics: [encoding, kv store, caching, sharding]
    difficulty: Medium
    solution: solution.md
    ---
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PROBLEMS_DIR = REPO / "problems"
INDEX = REPO / "PROBLEMS.md"

CATEGORY_LEGEND = [
    ("Basics",                  "Warm-up designs that test API design, caching and data model fundamentals"),
    ("Social & Feeds",          "Fan-out, timeline generation, hot users, recency vs personalization"),
    ("Real-Time Communication", "Low-latency delivery, presence, message ordering, end-to-end guarantees"),
    ("Reliability",             "Rate limiting, retries, circuit breakers, graceful degradation"),
    ("Search",                  "Inverted indexes, tries, ranking, prefix queries, autocomplete"),
    ("Streaming",               "Video and audio delivery, CDN, adaptive bitrate, transcoding pipelines"),
    ("Geospatial",              "Location indexing, proximity queries, real-time movement, matching"),
    ("Distributed Systems",     "Consistent hashing, replication, partitioning, coordination"),
    ("Messaging",               "Fan-out, retry, deduplication, durable delivery, multi-channel"),
]


def parse_frontmatter(path: Path) -> dict:
    text = path.read_text()
    if not text.startswith("---\n"):
        raise SystemExit(f"{path}: missing frontmatter")
    end = text.find("\n---\n", 4)
    if end == -1:
        raise SystemExit(f"{path}: unterminated frontmatter")
    block = text[4:end]
    meta: dict = {}
    for line in block.splitlines():
        if not line.strip() or ":" not in line:
            continue
        key, _, val = line.partition(":")
        meta[key.strip()] = val.strip()
    meta["id"] = int(meta["id"])
    topics = meta.get("topics", "[]").strip()
    if topics.startswith("[") and topics.endswith("]"):
        topics = topics[1:-1]
    meta["topics"] = [t.strip() for t in topics.split(",") if t.strip()]
    return meta


def load_all() -> list[dict]:
    rows = []
    for folder in sorted(PROBLEMS_DIR.iterdir()):
        if not folder.is_dir():
            continue
        q = folder / "question.md"
        if not q.exists():
            continue
        meta = parse_frontmatter(q)
        meta["folder"] = folder.name
        rows.append(meta)
    rows.sort(key=lambda r: r["id"])
    return rows


def render(rows: list[dict]) -> str:
    lines = [
        "# Problems Index",
        "",
        "A quick overview of every system design problem in this repo. Use the **Category**, **Difficulty** and **Topics** columns to filter by what you want to practice. Each row links to the problem statement and the reference solution.",
        "",
        "> This file is generated by `scripts/build_index.py` from the frontmatter in each problem's `question.md`. Do not edit by hand.",
        "",
        "| #  | Problem | Category | Topics | Difficulty | Question | Solution |",
        "|----|---------|----------|--------|------------|----------|----------|",
    ]
    for r in rows:
        topics = ", ".join(r["topics"])
        folder = r["folder"]
        sol = r.get("solution", "solution.md")
        lines.append(
            f"| {r['id']} | {r['title']} | {r['category']} | {topics} | {r['difficulty']} | "
            f"[Question](problems/{folder}/question.md) | "
            f"[Solution](problems/{folder}/{sol}) |"
        )

    lines += ["", "---", "", "### Category Legend", "",
              "| Category | What you practice |",
              "|----------|-------------------|"]
    used = {r["category"] for r in rows}
    for cat, desc in CATEGORY_LEGEND:
        if cat in used:
            lines.append(f"| {cat} | {desc} |")

    lines += [
        "",
        "### Difficulty Guide",
        "",
        "* **Easy** — Warm-up. Solvable in a 30 to 45 minute interview slot.",
        "* **Medium** — Standard onsite question. Has at least one non-obvious trade-off.",
        "* **Hard** — Senior-level. Multiple right answers; you must defend yours.",
        "",
        "> New problems land regularly. See [CONTRIBUTION.md](CONTRIBUTION.md) if you want to add one.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    check = "--check" in argv
    rows = load_all()
    if not rows:
        print("No problems found.", file=sys.stderr)
        return 1
    if len(rows) != len({r["id"] for r in rows}):
        raise SystemExit("Duplicate problem ids detected")

    new = render(rows)
    if check:
        current = INDEX.read_text() if INDEX.exists() else ""
        if current != new:
            print("PROBLEMS.md is stale. Run: python3 scripts/build_index.py", file=sys.stderr)
            return 1
        print("PROBLEMS.md is up to date.")
        return 0

    INDEX.write_text(new)
    print(f"Wrote {INDEX.relative_to(REPO)} ({len(rows)} problems).")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
